### ISSUE TITLE
got error when run "dotnet build --configuration Release"

### ISSUE THREAD

**Issue by winterwy** [MicrosoftDocs/mslearn-tailspin-spacegame-web#2257]
following instruction "https://docs.microsoft.com/en-us/learn/modules/create-a-build-pipeline/3-build-locally"

run "dotnet build --configuration Release" 
got below error. 

C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\temp\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web.sln]
C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error :   No such host is known. [C:\temp\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web.sln]

**Comment by winterwy** [comment]
proxy issue, fixed

**Comment by dhoegl** [comment]
@winterwy can you please explain the 'proxy issue' you had that caused this error? I am having the same issue. Thanks!
