### ISSUE TITLE
Unit tests branch

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/mslearn-tailspin-spacegame-web#2913]
Couple of comments on the Learn content...

1. The personal clone already has the branch(es) so the retrieving the branch from upstream is not necessary, though I can see the benefit of getting the upstream since it's the latest code irrespective of when the personal fork was made.
2. Rather than a fetch/branch you can just use `git checkout --track upstream/unit-tests`.
3. The paragraph 
`A TRX file is an XML document that contains the results of a test run. It's a popular format for NUnit tests because Visual Studio and other tools can help you visualize the results.` 
would be better as 
`A TRX file is an XML document that contains the results of a test run. It's a popular format for test results because Visual Studio and other tools can help you visualize the results.`
4. I also hit the issue mentioned in #1288 regarding the SDK version of the pipeline and have created a pull request to fix it

**Comment by phatcher** [comment]
Additionally when I run the code coverage locally, it fails to generate any code coverage, though it did work in the Azure Pipeline, updating coverlet.msbuild to 2.8.1 in the test project fixed this, though the test coverage changes slightly as test projects are no longer included.

**Comment by tpetchel** [comment]
I'm sorry that we haven't responded to this issue sooner. I'm closing this as we've made several updates to this content since this issue was filed. 

Also noting your points about `git checkout --track` and revising that sentence. I'll take a look at updating these! Thank you!!
