### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by FMartull** [MicrosoftDocs/mslearn-tailspin-spacegame-web#3016]
Hello,

Sorry, I am not a programer.

Following instructions from "https://docs.microsoft.com/en-us/learn/modules/create-a-build-pipeline/3-build-locally"

run "_dotnet build --configuration Release_"

I got below error:

`  It was not possible to find any compatible framework version
  The framework 'Microsoft.NETCore.App', version '2.0.7' was not found.
    - The following frameworks were found:
        3.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

  You can resolve the problem by installing the specified framework and/or SDK.

  The specified framework can be found at:
    - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.7&arch=x64&rid=win10-x64
C:\Users\user\\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(121,5): error : rzc generate exited with code -2147450730. [C:\REPOS\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web\Tailspin.SpaceGame.Web.csproj]

Build FAILED.

C:\Users\user\\.nuget\packages\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(121,5): error : rzc generate exited with code -2147450730. [C:\REPOS\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web\Tailspin.SpaceGame.Web.csproj]
    0 Warning(s)
    1 Error(s)`

The specified framework has reached end of life. What should I do? 

Thank you

**Comment by tpetchel** [comment]
Hi @FMartull - thanks for your interest in this content, and sorry for the late reply.

The app does indeed target .NET Core 3.1, so I'm puzzled why you're seeing that error message. I know you've moved on from this, but if you're interested in trying again, I would first make sure you're synchronized to the upstream repo (meaning, synchronized to this repo and not your fork):

```bash
git pull upstream master
```

And then run the `dotnet build` command again. 

If it still doesn't work, feel free to reactivate this issue. But I'm not sure what else I would try. But keep in mind that you build & run the app locally just to experience the development workflow; the rest of the module should work just fine even if you skip this part. 

Sorry I don't have a better answer!
