### ISSUE TITLE
npm: command not found

### ISSUE THREAD

**Issue by ylr-research** [MicrosoftDocs/mslearn-tailspin-spacegame-web#3071]
Following the [steps](https://docs.microsoft.com/en-us/learn/modules/host-build-agent/4-create-build-agent) for creating a build agent. In step 4, when running `sudo ./build-tools.sh` I get an error **npm: command not found**. If I continue on, eventually when creating the build-agent there is no **capability** listed for `npm`, which causes in the next step (pushing code changes) the build agent to fail for the same reason. 

See below for more details

![image](https://user-images.githubusercontent.com/63487874/82937011-6f854000-9f5d-11ea-922b-feee51dd9573.png)

Step 7: Capabilities expects `npm` directory to be listed

![image](https://user-images.githubusercontent.com/63487874/82937624-7bbdcd00-9f5e-11ea-8f96-912ea9ddc9a4.png)

Instead I get this

![image](https://user-images.githubusercontent.com/63487874/82937692-96904180-9f5e-11ea-8ed0-d1e4d93a4b6b.png)

Final result (Job failure)

![image](https://user-images.githubusercontent.com/63487874/82937877-e838cc00-9f5e-11ea-8625-bb8e71173839.png)

**Comment by tpetchel** [comment]
Hi @ylr-research,

Thanks for reporting this! I did a refresh pass through this module, and discovered that npm now needs to be installed explicitly in the script. 

I updated the steps and verified the module. The updates will go out later today.

Please feel free to reopen the issue if you still encounter problems! 
Thanks again for the report.
