### ISSUE TITLE
Exercise - Create the pipeline - Yml file fails with 3.1.300

### ISSUE THREAD

**Issue by eliassal** [MicrosoftDocs/mslearn-tailspin-spacegame-web#3955]
I am following the lab at 
https://docs.microsoft.com/en-us/learn/modules/create-a-build-pipeline/6-create-the-pipeline  
reached step 

> Add build tasks

the step 

> Build the project - Release

 fails complaining about dotnet sdk version as you can notice in the snapshot. 

I saw an issue here and someone suggested to switch to 2.2.x, which worked fine for me also. I think you need to revise your code with contents on MSLearn labs regularly and update to follow along with Azure changes as this is very frustrating and we can't open an issue for the lab team. 2nd, I saw someone who is suggesting to reset code, hard reset........, this is not really not a good approach.
Question, when writing Yaml pipeline, is there any intellisense or good doc to follow?
![BuildFail](https://user-images.githubusercontent.com/8447864/88683123-c4773b00-d0f3-11ea-992a-06148045ade0.jpg)

**Comment by tpetchel** [comment]
I'm sorry that we haven't responded to this issue sooner. I'm closing this as we've made several updates to this content since this issue was filed. But please feel free to open a new issue if you get stuck.

**Comment by eliassal** [comment]
But can you please respond to my queries and what I need to do in order to make this work?
