### ISSUE TITLE
Where is droped the file buildinfo.txt when yaml build runs

### ISSUE THREAD

**Issue by eliassal** [MicrosoftDocs/mslearn-tailspin-spacegame-web#3956]
I am following the lab at https://docs.microsoft.com/en-us/learn/modules/create-a-build-pipeline/6-create-the-pipeline, 7th step

Write build info
which succeeds but I am not able where this file is written, I check the succesful build but nothing is there, no zip file in a drop directory, where are the artifacts?
![BuildFail_003](https://user-images.githubusercontent.com/8447864/88684478-3734e600-d0f5-11ea-9cf1-fc8fa8164a02.jpg)

**Comment by troutt** [comment]
This is explained in the next exercise of the learning module. 
https://docs.microsoft.com/en-us/learn/modules/create-a-build-pipeline/7-publish-build-result

**Comment by eliassal** [comment]
Thanks

**Comment by eliassal** [comment]
OK Troutt, I continued the exercise and replaced 

> dotnetSdkVersion: '3.1.300' by '5.x' as wella s the ubuntu image from 'ubuntu-18.04' to 'ubuntu-20.04'

The pipeline fails with the following errors. In fact, I forked your repo in July last year, and not sure if I need to restart from 0, any idea on what is needed to be changed in my forked/generated github repo?

**Comment by tpetchel** [comment]
I'm sorry that we haven't responded to this issue sooner. You can use `git pull upstream <branch-name>` to pull down the latest changes. However, since this is for learning purposes, you might consider deleting your fork and forking again to get a fresh copy of everything.
