### ISSUE TITLE
Error "dotnet run --configuration Release --no-build --project Tailspin.SpaceGame.Web"

### ISSUE THREAD

**Issue by harten11** [MicrosoftDocs/mslearn-tailspin-spacegame-web#3988]
Hi all, 

I am working on the Microsoft course "creat a build pipeline". 

The Exercise "Build and run the web application" in the chapter  "Get the sample application" does not provide the expected results. 

I was able to run the following command "dotnet build -- configuration Release" (0 warnings; 0 errors), however I receive an error on the next step: 

UCHHAR@LT2753 MINGW64 ~/mslearn-tailspin-spacegame-web/Tailspin.SpaceGame.Web (master)
$ dotnet run --configuration Release --no-build --project Tailspin.SpaceGame.Web
'Tailspin.SpaceGame.Web' is not a valid project file.

I really hope you can help me, since I do not seem to find the answer on Google and am not very familiair with Visual Studio Code or Bash. 

Thanks in advance.

**Comment by dhoegl** [comment]
Same issue here. Dotnet Build seems to proceed correctly. But when launching Dotnet Run, the same error as mentioned above occurs for me.
Please advise. Thank you!

**Comment by tpetchel** [comment]
I'm sorry that we haven't responded to this issue. I'm closing it since the issue is older and I haven't been able to reproduce it for myself. But please feel free to reopen if this issue continues for anyone!

**Comment by aliqureshi789** [comment]
Correct command....

PS C:\azure\Devi_NET_WorkShop\AzureAppDevWorkshops\Azure App Service> dotnet run --configuration Release --no-build --project Tailspin.SpaceGame.Web
