### ISSUE TITLE
Continuous error: 'Tailspin.SpaceGame.Web' is not a valid project file

### ISSUE THREAD

**Issue by dhoegl** [MicrosoftDocs/mslearn-tailspin-spacegame-web#4008]
Hi all,

I am working on the Microsoft course <B>"create a build pipeline with Azure Pipelines".</B>

The Exercise "Build and run the web application" in the chapter "Get the sample application" does not provide the expected results in Visual Studio Code.

I was able to run the following command in VS Code:
<I>"$ dotnet build --configuration Release"</I> with no warnings or errors.

But when executing the following command, I am receiving the <B>"'Tailspin.SpaceGame.Web' is not a valid project file."</B> error,
<I>"$ dotnet run --configuration Release --no-build --project Tailspin.SpaceGame.Web"</I>

Please advise how to resolve this. No answers are showing up in web searches, and others have experienced the same issue without answers.

Thanks in advance.

**Comment by ibunker** [comment]
Hi,

had same issue if you check the last entries in the build command you can see the projects being restored. In my case noted .csproj at end. If add .csproj at the run command eg ......Web.csproj it seems to work.

**Comment by westerntc-mcgov** [comment]
so its 2 years later, and I ran into the same issue.  Is it something specific about the terminal or OS that the .csproj is needed?

I followed the instructions here: https://learn.microsoft.com/en-us/training/modules/create-a-build-pipeline/3-build-locally  

If everyone needs.csproj, shouldn't you update that text in the course item?

**Comment by tpetchel** [comment]
@westerntc-mcgov - I'm sorry we didn't resolve this better for you when you first reported it. The [documentation for dotnet run](https://learn.microsoft.com/dotnet/core/tools/dotnet-run) says `--project` can be a directory or file name, and both have always worked for me.

I'm happy to change this to show the full path, but I'm curious why it's not working for you. Can you please report back:

* What OS you're using.
* What terminal you're using to run `dotnet run`. I know it's in the VS Code terminal, but is Git Bash, PowerShell, something else?
* What version of dotnet you're using. Run `dotnet --version` if you're not sure.

Thank you!

**Comment by westerntc-mcgov** [comment]
OS: Windows 10 Pro - 21H2
OS Build: 19044.1889
Experience: Windows Feature Experience Pack 120.2212.4180.0

VIsual Studio Version 
17.3.3 (says its using .Net Framework 4.8.09037)  ( I don't know if you need all the installed products as its lengthy)
In my case I have VS 2022 Pro.   

I right click on projec> Open in terminal (its a Developer Powershell terimanl inside of VS 2022)

Powershell version is:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682

dotnet version: 6.0.400


(Just to reiterate I tried this in VIsual Studio Pro (proper not VS Code)  Now maybe that's what's really going on? But given I know people that get confused between the two, and already had the license for Pro, I was trying it in that.)  (So I actually already knew how to get repos from GitHub and just created / cloned in the GUI.  The app runs fine if you hit the Run (Play button) in the tool bar)

adding the .csproj did work when the other did not, I am just curious why it is needed in Visual Studio.  (Maybe I should go download VS Code and see if its different?)

**Comment by dhoegl** [comment]
Outdated and responses too late to help.
