### ISSUE TITLE
Error while running the command : dotnet run --configuration Release --no-build --project Tailspin.SpaceGame.Web

### ISSUE THREAD

**Issue by swapnilagashe** [MicrosoftDocs/mslearn-tailspin-spacegame-web#4497]
I am getting the folllowing error when I try to run. `dotnet run --configuration Release --no-build --project Tailspin.SpaceGame.Web`

`The application to execute does not exist: '/Users/DATA/projects/mslearn-tailspin-spacegame-web/Tailspin.SpaceGame.Web/bin/Release/netcoreapp3.1/Tailspin.SpaceGame.Web.dll'`

Any idea why this is happening?

**Comment by tpetchel** [comment]
I'm sorry for not replying sooner. I'm also sorry the command failed for you.
We recently did a refresh of this content. If you're still interested, please try it again. If it continues to fail, please reopen this or submit a new issue. Thanks!
