### ISSUE TITLE
Inefficient C# / .NET code pattern

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/mslearn-tailspin-spacegame-web#5295]
On [`GetItemsAsync`](https://github.com/MicrosoftDocs/mslearn-tailspin-spacegame-web/blob/main/Tailspin.SpaceGame.Web/LocalDocumentDBRepository.cs#L48), the` List<T>` is converted to an `IQueryable<T>`. That wraps the `IEnumerable<T>` into an [`EnumerableQuery<T>`](https://source.dot.net/#System.Linq.Queryable/System/Linq/EnumerableQuery.cs,1b681f4a078e4990,references) and the source will now be presented as an `IQueryable<T>`.

Now, all those lambdas will be expression trees instead of delegates and will have to be compiled to IL to be executed.

The same goes for the [`CountItemsAsync`](https://github.com/MicrosoftDocs/mslearn-tailspin-spacegame-web/blob/main/Tailspin.SpaceGame.Web/LocalDocumentDBRepository.cs#L72).

**Comment by tpetchel** [comment]
@paulomorgado - thanks for reporting this! I don't know why in the world this was so complex, but #5813 should help simplify things. Let us know if this isn't the fix you had in mind. Thanks again.
