### ISSUE TITLE
cannot convert from 'System.Linq.Expressions.Expression<System.Func>' to 'System.Func' [Tailspin.SpaceGame.Web.Tests]csharp(CS1503)

### ISSUE THREAD

**Issue by john-par** [MicrosoftDocs/mslearn-tailspin-spacegame-web#5852]
@tpetchel, I'm triaging two Customer Feedback work items related to mslearn-tailspin-spacegame-web:

* [CUSTOMER FEEDBACK 535277 | Errors in Run quality tests in your build pipeline by using Azure Pipelines](https://dev.azure.com/ceapex/Microsoft%20Learn/_workitems/edit/535277)
* [CUSTOMER FEEDBACK 535628 | Build failure in module - Run quality tests in your build pipeline by using Azure Pipelines](https://dev.azure.com/ceapex/Microsoft%20Learn/_workitems/edit/535628)

Both work items are related to the same issue. I've confirmed the issue locally:

```
$ dotnet build --configuration Release
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\v-jopar\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web\Tailspin.SpaceGame.Web.csproj (in 122 ms).
  Restored C:\Users\v-jopar\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web.Tests\Tailspin.SpaceGame.Web.Tests.csproj (in 502 ms).
  Tailspin.SpaceGame.Web -> C:\Users\v-jopar\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web\bin\Release\net5.0\Tailspin.SpaceGame.Web.dll
  Tailspin.SpaceGame.Web -> C:\Users\v-jopar\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web\bin\Release\net5.0\Tailspin.SpaceGame.Web.Views.dll
C:\Users\v-jopar\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web.Tests\DocumentDBRepository_GetItemsAsyncShould.cs(43,17): error CS1503: Argument 1: cannot convert from 'System.Linq.Expressions.Expression<System.Func<TailSpin.SpaceGame.Web.Models.Score, bool>>' to 'System.Func<TailSpin.SpaceGame.Web.Models.Score, bool>' [C:\Users\v-jopar\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web.Tests\Tailspin.SpaceGame.Web.Tests.csproj]

Build FAILED.

C:\Users\v-jopar\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web.Tests\DocumentDBRepository_GetItemsAsyncShould.cs(43,17): error CS1503: Argument 1: cannot convert from 'System.Linq.Expressions.Expression<System.Func<TailSpin.SpaceGame.Web.Models.Score, bool>>' to 'System.Func<TailSpin.SpaceGame.Web.Models.Score, bool>' [C:\Users\v-jopar\mslearn-tailspin-spacegame-web\Tailspin.SpaceGame.Web.Tests\Tailspin.SpaceGame.Web.Tests.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.81
```

I checked the history of [mslearn-tailspin-spacegame-web/Tailspin.SpaceGame.Web.Tests/DocumentDBRepository_GetItemsAsyncShould.cs](https://github.com/MicrosoftDocs/mslearn-tailspin-spacegame-web/blob/unit-tests/Tailspin.SpaceGame.Web.Tests/DocumentDBRepository_GetItemsAsyncShould.cs) and I'm not seeing any recent changes that might be causing the issue. That's as far as my level of expertise can take me. Please have a look at the file when you get a moment. Thanks.

**Comment by zcaspall** [comment]
I'm completing this course right now and came to this issue to find the solution, but I ended up fixing it myself by putting .Compile() after the call to queryPredicate.

**Comment by tpetchel** [comment]
@john-par - thanks for reporting. I made some changes the other week, and apparently forgot to apply them to the `unit-tests` branch. (The fix was to remove the `Expression` wrapper from the query expression.)

I pushed up a fix just now. If you fetch the latest `unit-tests` branch, `dotnet build` and `dotnet test` should now succeed.

Sorry for trouble, and thanks again for reporting!
