### ISSUE TITLE
Can't do git fetch upstream release

### ISSUE THREAD

**Issue by mas-oliveira** [MicrosoftDocs/mslearn-tailspin-spacegame-web#5989]
While doing the following instructions:

git fetch upstream release
git checkout -B release upstream/release

The output is:
fatal: couldn't find remote ref release

**Comment by tpetchel** [comment]
Hi @mas-oliveira - I think the branch you're looking for is in another repo: https://github.com/MicrosoftDocs/mslearn-tailspin-spacegame-web-deploy (note the "-deploy" part at the end.) For the DevOps content, we pair GitHub repository per learning path.
