### ISSUE TITLE
 error NU1100: Unable to resolve 'Newtonsoft.Json (>= 12.0.1)' for '.NETCoreApp,Version=v2.1'

### ISSUE THREAD

**Issue by ayush1210** [MicrosoftDocs/mslearn-tailspin-spacegame-web#730]
I get this error when i build :-1: 
 error NU1100: Unable to resolve 'Newtonsoft.Json (>= 12.0.1)' for '.NETCoreApp,Version=v2.1'

**Comment by chrisburger90** [comment]
Were there any updates to this that resolved this issue? This is outside of my area of expertise but it's preventing me from continuing with the MS Learn module.

**Comment by chrisburger90** [comment]
Honestly I'd need to run through the module again to give you specific details. I had someone else build it and send me the files that included the dependency after they changed some things. I'll get back to you on this.

**Comment by hirenrpatel1610** [comment]
I am also facing the same issue.

**Comment by roblaird-personal** [comment]
This is also outside of my skillset, but I resolved this by:

1. The build error message states that it cannot find version <= 12.0.1 but found the nearest version 9.0.1.
2. In Visual Studio, open the NuGet Package Manager (Menu bar, Project/Manage NuGet Packages...
3. Locate Newtonsoft.json, change version from 12.0.1 to 9.0.1.
4. Build again, should be good to go.

**Comment by ciprianglg** [comment]
How i solve it on my side:
Using VSC i've opened terminal, and i went to the folder where i have the project:
1. cd .\Tailspin.SpaceGame.Web\
2. dotnet add package Newtonsoft.Json

After this dotnet build --configuration Release succeed.

**Comment by Meg-Nid** [comment]
none of the above resolutions worked for me
even i'm getting the same error, can someone please help

**Comment by tpetchel** [comment]
Apologies for any issues folks encountered while building the app. We've removed the dependency on this package, so you won't see that error going forward. Closing this for now.
